### ISSUE TITLE
Rosetta ne fonctionne pas

### ISSUE THREAD

**Issue by trebmuh** [franck-paul/rosetta#2]
Fin août, je cherchais un greffon qui me permettrait d'avoir des billets en plusieurs langues.
Tu (Franck-Paul) m'as conseillé de regarder du côté de Rosetta, ce que j'ai fait.
J'ai donc téléchargé la version 0.8, l'ai décompressée, l'ai placée dans htdocs/dotclear/dotclear/plugins/ .
Elle apparaît bien dans mon interface admin de dotclear.
Lorsque je tente de "créer une nouvelle traduction" à partir d'un billet déjà existant et déjà publié,
J'arrive à ça : 

![1598647845](https://user-images.githubusercontent.com/8705846/98122923-84bdad80-1eb1-11eb-8ca4-7f1e4a916548.png)

Mais je ne peux pas cliquer sur "Annuler" ou "Créer". Enfin si, je peux cliquer, mais il ne se passe rien !

Voici des captures d'écran ;

![1](https://user-images.githubusercontent.com/8705846/98123113-bf274a80-1eb1-11eb-9fdb-6065a5696005.png)

![2](https://user-images.githubusercontent.com/8705846/98123127-c2bad180-1eb1-11eb-97f2-86a9eec3af8b.png)

![3](https://user-images.githubusercontent.com/8705846/98123227-dbc38280-1eb1-11eb-8e0b-f257ea400dc8.png)

Tu m'as dit sur IRC que les deux premiers onglets (billets / pages) ne sont pas encore développés et qu'il est donc normal qu'ils soient vides.

Ensuite, tu m'as dis que tu avais fait un test de ton côté (création billet FR, puis création traduction EN et DE) et que tu n'avais pas eu de souci. Là, tu as suggéré que c'était peut-être un problème côté javascript et m'a demandé de regardé ce que la console indiquait.

Les infos de firefox "68.11.0esr (64 bits)" -> menu -> développement web -> "console du navigateur" sont :

![dotclear-erreur-javascript](https://user-images.githubusercontent.com/8705846/98123568-4eccf900-1eb2-11eb-8337-997719298746.png)

On peut voir le : `Loading failed for the <script> with source “https://librazik.tuxfamily.org/dotclear/dotclear/admin/index.php?pf=rosetta/js/popup_new.js&v=0.8”` qui semble être le soucis puisque tu en as dis que :

> c'est justement le script javascript qui gère l'interaction quand tu veux créer une traduction. Maintenant faudrait savoir pourquoi il n'est pas chargé. Il faudrait regarder la console de la popup : clic sur “Créer une nouvelle traduction", une popup doit s'ouvrir et à ce moment il faudrait afficher la console (associée à cette popup donc) et voir s'il y a plus d'info à propos de cette erreur de chargement.

Ensuite, j'ai manqué de temps pour continuer l'investigation et je reprends maintenant.

----

Je me place sur un billet déjà publié (en "fr") , je clique sur "Créer une traduction", je fais `Ctrl + Maj +J`pour faire afficher la console du navigateur de firefox "78.4.0esr (64 bits)", et je rempli les champs :

![4](https://user-images.githubusercontent.com/8705846/98125297-9b193880-1eb4-11eb-8c28-a8242ccf305f.png)

La console du navigateur me donne :

![5](https://user-images.githubusercontent.com/8705846/98126031-6954a180-1eb5-11eb-9b3e-219824a00c26.png)

et rien de plus lorsque je clique sur le bouton "créer".

Voilà pour un résumé de là où j'en suis.

**Comment by franck-paul** [comment]
Une extension (uBlock) qui empêchait le chargement du script. On ferme.
